'use strict';
const fs = require('fs');
const pathToReport = 'report.json';
const reportJson = JSON.parse(fs.readFileSync(pathToReport));
const reportHeader = `<!DOCTYPE html><html>
<head>
    <title>cucumber-json-reporter-to-html</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="./css/custom.css" type="text/css"/>
    <meta charset="UTF-8">
</head>
<body>
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand">cucumber-json-reporter-to-html</a>
            <div class="project-name visible-md visible-lg">Your-Project</div>
            <div class="label-container">
                <span class="label label-success" title=scenarios>Passed: ${getResult('passed')}</span>
                <span class="label label-danger" title=scenarios>Failed: ${getResult('failed')}</span>
                <span class="label label-skipped" title=scenarios>Skipped: ${getResult('skipped')}</span>
            </div>
        </div>
    </div>
</div>`;

const reportEnd = `<div> &nbsp<br> &nbsp </div>
<div class="navbar-fixed-bottom row-fluid footer-div ">
<div class="navbar-inner">
    <div class="footer-container">
        <a target="_blank" href="https://www.npmjs.com/package/cucumber-json-reporter-to-html">
            <div class="text-muted footer-link">
                generated by @cucumber-json-reporter-to-html
            </div>
        </a>
    </div>
</div>
</div></body></html>`;
function create({ source, dest, title, description }) {

}
function getResult(status) {
    let result = 0;
    reportJson.map((feature) => {
        feature.elements.map((scenario) => {
            scenario.steps.map((step) => {
                if (step.result.status === status) { result++; }
            });
        });
    });
    return result;
}

function getStepColor(step) {
    let cssClass;
    switch (step.result.status) {
        case 'passed':
            cssClass = 'label-success';
            break;
        case 'failed':
            cssClass = 'label-danger';
            break;
        case 'skipped':
            cssClass = 'label-skipped';
            break;
    }
    return cssClass;
}

function generateScenarioHtml(scenarioArray, featureIndex) {
    let scenarioHtml = '';
    scenarioArray.forEach((scenario) => {
        scenarioHtml = scenarioHtml + `
        <div class="scenario ${getScenarioStatus(scenario.steps)}">
        <div>
            <strong>${scenario.name}</strong>
            <div style="text-align:right;">total time</div>
        ${generateStepsHtml(scenario.steps, scenario.name)}</div></div>`;
    });
    return scenarioHtml;
}

function generateStepsHtml(stepsArray, scenarioName) {
    let stepsHtml = '';
    stepsArray.forEach((step) => {
        if (step.keyword !== 'After') {
            stepsHtml = stepsHtml + `<div class="steps ${getStepColor(step)}">${step.name}<div style="text-align:right;">total time1</div></div>`
        }
        else {
            if (step.embeddings !== undefined) {
                let image = new Buffer.from(step.embeddings[0].data, 'base64');
                fs.existsSync('screenshots') || fs.mkdirSync('screenshots');
                let screenshotPath = './screenshots/' + scenarioName.replace(/\s/g, '') + '.png';
                fs.writeFileSync(screenshotPath, image, 'base64');
                stepsHtml = stepsHtml + `<img src='${screenshotPath}'>`;
            }
        }
    });
    return stepsHtml;
}

function generateHtmlForFeature(jsonData) {
    let reportFillingHtml = '';
    let featureIndex = 0;
    jsonData.forEach((feature) => {
        reportFillingHtml = reportFillingHtml + `<div class="container">
        <h3 class="all-features ${getFeatureStatus(feature.elements)}">${feature.name}</h3>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#feature${featureIndex}">more details</button>
        <div id="feature${featureIndex}" class="collapse">${generateScenarioHtml(feature.elements, featureIndex)}</div></div></div>`
        featureIndex++;
    });
    return reportFillingHtml;
}

function getFeatureStatus(elements) {
    elements = elements.filter((element) => {
        if (getScenarioStatus(element.steps) === 'label-failed') { return element; }
    });
    return elements.length > 0 ? 'label-failed' : 'label-passed';
}

function getScenarioStatus(steps) {
    steps = steps.filter((step) => {
        if (step.result.status === 'failed') return step;
    });
    return steps.length > 0 ? 'label-failed' : 'label-passed';
}

let finalHtml = reportHeader + generateHtmlForFeature(reportJson) + reportEnd;
fs.writeFileSync('report.html', finalHtml.toString(), 'utf8');